import React from 'react';

export const metadata = {
  title: 'My Next.js App',
  description: 'Generated by Next.js',
};

export default function MarketingLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
     <body>
    
      
       {children}


<footer style = {{backgroundColor:"ghostwhite", padding:"1rem", alignItems:"center", justifyContent:"center", display:"flex"}}>
  <p style= {{backgroundColor:"grey", borderRadius: "20px" , color:"white", padding:"10px", width:"50px", boxShadow: "0 2px 8px rgba(0, 0, 0, 0.5)" , cursor:"pointer"}}>Footer</p>
</footer>

</body>

    </html>
  );
}
