
import {Metadata} from "next";


import {ErrorWrapper} from "./error-wrapper";

import { ThemeProvider } from "./renderDemo/components/theme-provider";

import Link from "next/link";

import React from 'react';

import "./globals.css";

import { ClerkProvider, Show, SignInButton, SignUpButton, UserButton, SignOutButton } from '@clerk/nextjs'
import { Geist, Geist_Mono } from 'next/font/google'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ClerkProvider>
          <header className="flex justify-end items-center p-4 gap-4 h-16">
            <Show when="signed-out">
              <SignInButton> 
                <button className="bg-cyan-400 text-white rounded-full font-medium text-sm sm:text-base h-10 sm:h-12 px-4 sm:px-5 cursor-pointer">
                  Sign In
                </button></SignInButton>
              <SignUpButton>
                <button className="bg-purple-700 text-white rounded-full font-medium text-sm sm:text-base h-10 sm:h-12 px-4 sm:px-5 cursor-pointer">
                  Sign Up
                </button>
              </SignUpButton>
            </Show>
            <Show when="signed-in">
              <UserButton />
              <Link href="/authentication/user-profile">Profile</Link>
              
              <SignOutButton />
            </Show>
          </header>
          {children}
        </ClerkProvider>
      </body>
    </html>
  )
}





export  function MarketingLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <ThemeProvider>
        <body>
          <header style = {{backgroundColor:"lightblue", padding:"1rem", alignItems:"center", justifyContent:"center", display:"flex"}}>
            <p style= {{backgroundColor:"blue", borderRadius: "20px" , color:"white", padding:"10px", width:"50px", boxShadow: "0 2px 8px rgba(0, 0, 0, 0.5)" , cursor:"pointer"}}>Header</p>
          </header>

      <ErrorWrapper> {children}</ErrorWrapper>
      
      


<footer style = {{backgroundColor:"ghostwhite", padding:"1rem", alignItems:"center", justifyContent:"center", display:"flex"}}>
  <p style= {{backgroundColor:"grey", borderRadius: "20px" , color:"white", padding:"10px", width:"50px", boxShadow: "0 2px 8px rgba(0, 0, 0, 0.5)" , cursor:"pointer"}}>Footer</p>
</footer>

</body>
</ThemeProvider>

    </html>
  );
}
